SET NAMES utf8mb4;
SET CHARACTER SET utf8mb4;

CREATE DATABASE IF NOT EXISTS agriculture_inventory CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE agriculture_inventory;

CREATE TABLE IF NOT EXISTS customers (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  phone VARCHAR(50),
  address TEXT,
  totalDebt DECIMAL(12,2) NOT NULL DEFAULT 0,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS suppliers (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  phone VARCHAR(50),
  address TEXT,
  totalBalance DECIMAL(12,2) NOT NULL DEFAULT 0,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS products (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  price DECIMAL(10,2) NOT NULL,
  stock INT NOT NULL DEFAULT 0,
  imagePath VARCHAR(500),
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS drivers (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  phone VARCHAR(50),
  vehiclePlate VARCHAR(100),
  vehicleDetails VARCHAR(100),
  isAvailable TINYINT(1) NOT NULL DEFAULT 1,
  totalBalance DECIMAL(12,2) NOT NULL DEFAULT 0,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS orders (
  id INT AUTO_INCREMENT PRIMARY KEY,
  orderNumber VARCHAR(50) NOT NULL UNIQUE,
  customerType ENUM('COMPANY', 'DRIVER') NOT NULL DEFAULT 'COMPANY',
  customerId INT NULL,
  totalAmount DECIMAL(12,2) NOT NULL,
  totalDelivery DECIMAL(12,2) NOT NULL DEFAULT 0,
  status ENUM('PENDING','ASSIGNED','DELIVERED','CANCELLED') NOT NULL DEFAULT 'PENDING',
  driverId INT,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (customerId) REFERENCES customers(id),
  FOREIGN KEY (driverId) REFERENCES drivers(id)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS order_items (
  id INT AUTO_INCREMENT PRIMARY KEY,
  orderId INT NOT NULL,
  productId INT NOT NULL,
  quantity INT NOT NULL,
  price DECIMAL(12,2) NOT NULL,
  deliveryFeePerTon DECIMAL(12,2) NOT NULL DEFAULT 0,
  totalDelivery DECIMAL(12,2) NOT NULL DEFAULT 0,
  FOREIGN KEY (orderId) REFERENCES orders(id),
  FOREIGN KEY (productId) REFERENCES products(id)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS payments (
  id INT AUTO_INCREMENT PRIMARY KEY,
  customerId INT NOT NULL,
  amount DECIMAL(12,2) NOT NULL,
  method ENUM('CASH','BANK') NOT NULL DEFAULT 'CASH',
  senderName VARCHAR(255),
  notes VARCHAR(255),
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (customerId) REFERENCES customers(id)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS purchases (
  id INT AUTO_INCREMENT PRIMARY KEY,
  supplierId INT NOT NULL,
  totalAmount DECIMAL(12,2) NOT NULL,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (supplierId) REFERENCES suppliers(id)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS purchase_items (
  id INT AUTO_INCREMENT PRIMARY KEY,
  purchaseId INT NOT NULL,
  productId INT NOT NULL,
  quantity INT NOT NULL,
  price DECIMAL(12,2) NOT NULL,
  FOREIGN KEY (purchaseId) REFERENCES purchases(id),
  FOREIGN KEY (productId) REFERENCES products(id)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS supplier_payments (
  id INT AUTO_INCREMENT PRIMARY KEY,
  supplierId INT NOT NULL,
  amount DECIMAL(12,2) NOT NULL,
  method ENUM('CASH','BANK') NOT NULL DEFAULT 'CASH',
  senderName VARCHAR(255),
  note TEXT,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (supplierId) REFERENCES suppliers(id)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS supplier_ledger (
  id INT AUTO_INCREMENT PRIMARY KEY,
  supplierId INT NOT NULL,
  type ENUM('PURCHASE','PAYMENT') NOT NULL,
  amount DECIMAL(12,2) NOT NULL,
  referenceId INT,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (supplierId) REFERENCES suppliers(id)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS driver_payments (
  id INT AUTO_INCREMENT PRIMARY KEY,
  driverId INT NOT NULL,
  amount DECIMAL(12,2) NOT NULL,
  notes TEXT,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (driverId) REFERENCES drivers(id)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS driver_ledger (
  id INT AUTO_INCREMENT PRIMARY KEY,
  driverId INT NOT NULL,
  type ENUM('DELIVERY','PAYMENT','DEBT') NOT NULL,
  amount DECIMAL(12,2) NOT NULL,
  referenceId INT,
  notes TEXT,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (driverId) REFERENCES drivers(id)
) ENGINE=InnoDB;
